# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
 pipelines:
   - pipeline: buildContosoAir # identifier for the resource used in pipeline resource variables
     source: Student1-57230252.ContosoAir # name of the pipeline that produces the artifact
     trigger:
       branches:
        include:
          - master

pool:
  vmImage: ubuntu-latest
  name: default

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '8fb1a08e-8413-4a72-a84d-98e6ea6a9b8f'
    definition: '4'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Connection'
    subscriptionId: 'a4635f62-027d-4c43-9aa3-a88172c722af'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-lod'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
    csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Connection'
    appType: 'webApp'
    WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'


